services:
  server:
    image: palermo/envoy-filters-ext-proc:latest
    ports:
      - "50051:50051"
    volumes:
      - tmp-data:/tmp

  envoy:
    image: envoyproxy/envoy:v1.32-latest
    command:
      - "--config-path"
      - "/etc/envoy/envoy.yaml"
      - "--log-level"
      - "warn"
    ports:
      - "80:80"
      - "9001:9001"
    volumes:
      - tmp-data:/tmp
      - ./.container/envoy.yaml:/etc/envoy/envoy.yaml

volumes:
  tmp-data:
